name: gamelist
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  riverpod: ^2.3.2
  shared_preferences: ^2.0.20
  google_fonts: ^4.0.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.2
#   flutter_native_splash: ^2.2.19

# flutter_native_splash:
#   background_image: "assets/images/backgroud.png"
#   image: assets/images/splash.png
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
